name: Dispatch new tokens sent from figma
on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "original-tokens.json"
          json: ${{ github.event.client_payload.tokens }}
          dir: "src/tokens"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: rm -rf node_modules && pnpm i --frozen-lockfile

      - name: Transform tokens
        run: pnpm transform-tokens

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOTGITHUBTOKEN }}
          commit-message: "feat: update design tokens"
          title: "feat: update design tokens"
          body: |
            # Context
            - Design tokens have been updated via Figma and need to be reviewed.

            # This commit
            - Update tokens json file
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated-pr
